#!/usr/bin/bash

if [[ -z "${PKG_VERSION:-}" ]]; then
    echo "Set PKG_VERSION of the release";
    exit 1
fi

mkdir -p dist/rpm-macros-virtualenv-$PKG_VERSION
cp LICENSE README.md macros.python-virtualenv dist/rpm-macros-virtualenv-$PKG_VERSION/
cd dist
tar -czf rpm-macros-virtualenv-$PKG_VERSION.tar.gz rpm-macros-virtualenv-$PKG_VERSION

echo "Created dist/rpm-macros-virtualenv-$PKG_VERSION.tar.gz"
